config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do
  resources :alerts
  devise_for :users

  devise_scope :user do  
    get '/users/sign_out' => 'devise/sessions#destroy'     
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "alerts#index"
  mount Sidekiq::Web => "/sidekiq"
end

app/models/alert.rb
class Alert < ApplicationRecord
    belongs_to :user
    enum :status, [ :inactive, :active ]
    def self.send_messages

        AlertMailer.send_alert_email(current_user.email,).deliver_now
    end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         has_many :alerts
end

app/controllers/alerts_controller.rb
class AlertsController < ApplicationController
  before_action :set_alert, only: %i[ show edit update destroy ]
  before_action :authenticate_user!
  # GET /alerts or /alerts.json
  def index
    @alerts = Alert.paginate(page: params[:page], per_page: 10)
  end

  # GET /alerts/1 or /alerts/1.json
  def show
  end

  # GET /alerts/new
  def new
    @alert = Alert.new
  end

  # GET /alerts/1/edit
  def edit
  end

  # POST /alerts or /alerts.json
  def create
    @alert = Alert.new(alert_params)

    respond_to do |format|
      if @alert.save
        format.html { redirect_to alert_url(@alert), notice: "Alert was successfully created." }
        format.json { render :show, status: :created, location: @alert }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @alert.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /alerts/1 or /alerts/1.json
  def update
    respond_to do |format|
      if @alert.update(alert_params)
        format.html { redirect_to alert_url(@alert), notice: "Alert was successfully updated." }
        format.json { render :show, status: :ok, location: @alert }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @alert.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /alerts/1 or /alerts/1.json
  def destroy
    @alert.destroy

    respond_to do |format|
      format.html { redirect_to alerts_url, notice: "Alert was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_alert
      @alert = Alert.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def alert_params
      params.require(:alert).permit(:user_id, :cryptocurrency, :target_price, :status)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/alerts_helper.rb
module AlertsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/crypto_price_alert.rb
require 'net/http'


module CryptoPriceAlert
API_URL = "https://api.coingecko.com/api/v3/coins/markets?vs_currency=USD&order=ma
rket_cap_desc&per_page=100&page=1&sparkline=false"

    def current_price(crypto_currency)
        url = URI(API_URL)
        https = Net::HTTP.new(url.host, url.port)
        https.use_ssl = true

        request = Net::HTTP::Get.new(url)
        AlertMailer.send_alert_email("dishebh27@gmail.com").deliver_now
        response = https.request(request)
        #puts response.read_body
        #request = Net::HTTP::Post.new(url, form_data)
        
        responses = JSON.parse(response.read_body)
        for res_hash in responses do
          if res_hash["id"] == crypto_currency
            return res_hash["current_price"]
          end
        end
        return nil

    end
end

app/views/alerts/_alert.html.erb
    <tr>
    <th scope="row"></th>
      <td><%= alert.cryptocurrency %></td>
      <td><%= alert.target_price %></td>
      <td><%= alert.status %></td>
      <td> <%= link_to "Show this alert", alert %></td>
    </tr>
  

app/views/alerts/_form.html.erb
<%= form_with(model: alert) do |form| %>
  <% if alert.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(alert.errors.count, "error") %> prohibited this alert from being saved:</h2>

      <ul>
        <% alert.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.number_field :user_id , type: :hidden , value: current_user.id %>
  </div>

  <div>
    <%= form.label :cryptocurrency, style: "display: block" %>
    <%= form.text_field :cryptocurrency %>
  </div>

  <div>
    <%= form.label :target_price, style: "display: block" %>
    <%= form.text_field :target_price %>
  </div>

  <div>
    <%= form.label :status, style: "display: block" %>
    <%= form.text_field :status , value: :active %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/alerts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      
      <% if user_signed_in? %>
      <li class="nav-item active">
      <%= link_to "All Alerts" , alerts_path , class: "nav-link" %>
      </li>
      <li class="nav-item">
      <%= link_to "Sign Out" , destroy_user_session_path , method: :delete , class: "nav-link" %>
      </li>
      <% else %>
      <li class="nav-item">
      <%= link_to "Sign In" , new_user_session_path , class: "nav-link" %>
      </li>
      <li class="nav-item">
      <%= link_to "Sign Up" , new_user_registration_path , method: :delete , class: "nav-link" %>
      </li>

      <% end %>
      
    </ul>
    
  </div>
</nav>

app/views/alerts/edit.html.erb
<h1>Editing alert</h1>

<%= render "form", alert: @alert %>

<br>

<div>
  <%= link_to "Show this alert", @alert %> |
  <%= link_to "Back to alerts", alerts_path %>
</div>

app/views/alerts/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Alerts</h1>

<div id="alerts">
<table class="table">
<thead class="thead-dark">
<tr>
  <th scope="col">#</th>
  <th scope="col">Cryptocurrency</th>
  <th scope="col">Target price</th>
  <th scope="col">Status</th>
  <th scope="col">View Alert</th>
</tr>
</thead>
<tbody>
<div class="apple_pagination">
  <%= will_paginate @alerts, :container => false %>
</div>
  <% @alerts.each do |alert| %>
    <tr>
    <%= render alert %>
    
    
  <% end %>
  </tbody>
  
  
  </table
</div>

<%= link_to "New alert", new_alert_path %>

app/views/alerts/new.html.erb
<h1>New alert</h1>

<%= render "form", alert: @alert %>

<br>

<div>
  <%= link_to "Back to alerts", alerts_path %>
</div>

app/views/alerts/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @alert %>

<div>
  <%= link_to "Edit this alert", edit_alert_path(@alert) %> |
  <%= link_to "Back to alerts", alerts_path %>

  <%= button_to "Destroy this alert", @alert, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <title>Hello, world!</title>
  </head>
  
    
    <body>
    
    <%= render 'alerts/header' %>
    <p class="alert"><%= alert %></p>
    <div class="container">
    <%= yield %>
    </div>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>